# Generated by Django 2.2 on 2020-12-14 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201212_2101'),
        ('userforms', '0002_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='owner',
        ),
        migrations.AddField(
            model_name='device',
            name='firm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FirmProfile'),
        ),
        migrations.AddField(
            model_name='driver',
            name='firm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FirmProfile'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='firm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FirmProfile'),
        ),
    ]
