# Generated by Django 2.2 on 2020-12-14 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20201212_2101'),
        ('userforms', '0003_auto_20201214_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userforms.Device')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userforms.Driver')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FirmProfile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userforms.Vehicle')),
            ],
        ),
    ]
