# Generated by Django 2.2 on 2020-12-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userforms', '0004_auto_20201215_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='chart_parameters',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_parameters',
            field=models.TextField(default='EDT,LAT,LNG,RNO,'),
        ),
    ]
