# Generated by Django 2.2 on 2020-12-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userforms', '0005_auto_20201218_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='delay',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='device',
            name='is_UTC',
            field=models.BooleanField(default=False),
        ),
    ]
