# Generated by Django 2.2 on 2021-01-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userforms', '0006_auto_20201218_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='no_of_extraparams',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='no_of_mainparams',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='no_of_vehicalparams',
            field=models.IntegerField(default=0),
        ),
    ]
