# Generated by Django 2.2 on 2020-10-27 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mmlinkdata1',
        ),
    ]
