# Generated by Django 2.2 on 2020-11-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='usertype',
            field=models.CharField(choices=[('Driver', 'Driver'), ('Owner', 'Owner'), ('SysAdmin', 'SysAdmin')], max_length=100, null=True),
        ),
    ]
