# Generated by Django 2.2 on 2020-12-12 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_firmprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='firm_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.FirmProfile'),
        ),
    ]
