# Generated by Django 2.2 on 2020-12-12 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userprofile_firm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='firm_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FirmProfile'),
        ),
    ]
