# Generated by Django 2.2 on 2021-01-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201212_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=100)),
                ('s1_start', models.DateTimeField(null=True)),
                ('s1_end', models.DateTimeField(null=True)),
                ('s1_error', models.CharField(max_length=100, null=True)),
                ('s2_start', models.DateTimeField(null=True)),
                ('s2_end', models.DateTimeField(null=True)),
                ('s2_error', models.CharField(max_length=100, null=True)),
                ('s3_start', models.DateTimeField(null=True)),
                ('s3_end', models.DateTimeField(null=True)),
                ('s3_error', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
