# Generated by Django 2.2 on 2021-01-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_stationreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationreport',
            name='s1_end',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stationreport',
            name='s1_error',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stationreport',
            name='s1_start',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stationreport',
            name='s2_end',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stationreport',
            name='s2_error',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stationreport',
            name='s2_start',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stationreport',
            name='s3_end',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stationreport',
            name='s3_error',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stationreport',
            name='s3_start',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
