# Generated by Django 2.2 on 2021-01-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_tagassign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagassign',
            name='vin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
