# Generated by Django 2.2 on 2020-12-22 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userforms', '0006_auto_20201218_2210'),
        ('app', '0008_auto_20201212_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TRIP_ID', models.IntegerField()),
                ('STARTEDT', models.DateTimeField()),
                ('ENDEDT', models.DateTimeField(null=True)),
                ('STARTLAT', models.CharField(max_length=100)),
                ('ENDLAT', models.CharField(max_length=100, null=True)),
                ('STARTLNG', models.CharField(max_length=100)),
                ('ENDLNG', models.CharField(max_length=100, null=True)),
                ('STARTODO', models.FloatField()),
                ('ENDODO', models.FloatField(null=True)),
                ('STARTADDRESS', models.CharField(max_length=500)),
                ('ENDADDRESS', models.CharField(max_length=500, null=True)),
                ('MAX_SPEED', models.FloatField(null=True)),
                ('AVG_SPEED', models.FloatField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userforms.Device')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userforms.Driver')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FirmProfile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userforms.Vehicle')),
            ],
        ),
    ]
