# Generated by Django 2.2 on 2020-12-21 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ENDLNG',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='STARTLNG',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
