# Generated by Django 2.2 on 2020-12-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20201221_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='ENDLNG',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='STARTLNG',
            field=models.CharField(max_length=100),
        ),
    ]
